### ISSUE TITLE
Feature: User can add a new student

### ISSUE THREAD

**Issue by lisa-t-nguyen** [lisa-t-nguyen/final-project#3]
## ⚙️ Feature

Users can add a new student.

## 📐 Functionality

Users can fill out fields to add a new student with their first name, last name, date of birth, grade level, and their student ID number will be automatically populated. 

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/109618931/200925870-4b876684-8647-417b-84e5-5d2d609f2cf9.png)
![image](https://user-images.githubusercontent.com/109618931/200925955-b48e616d-5006-45bd-8b38-bb414f53552c.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to create a schema "students"
- [x] Update `schema.sql` to create a schema "studentGradeYears"
- [x] Update `data.sql` to insert into "students" (firstName, lastName, dateOfBirth)
- [x] Update `data.sql` to insert into "studentGradeYears" (gradeLevel, yearStart, yearEnd)

### ☁️ Server Tasks

- [x] Update `server/index.js` to require 'path'
- [x] Update `server/index.js` to require 'pg'
- [x] Update `server/index.js` to require 'express'
- [x] Update `server/index.js` to require 'dotenv/config'
- [x] Update `server/index.js` create a const db
- [x] Update `server/index.js` to create a const app for express
- [x] Update `server/index.js` to create a middleware
- [x] Update `server/index.js` to post a const sql when querying the database
- [x] Update `server/index.js` to listen on port for troubleshooting
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a NewStudent component to submit all user inputs for student's first name, last name, DOB, grade level, school year, and pre-populated student ID number
- [x] NewStudent component will have a constructor with current state
- [x] NewStudent component will have a handleSubmit method
- [x] NewStudent component will have a preventDefault method
- [x] NewStudent component will have a fetch to POST 
- [x] NewStudent component will have a FormData object and append user entries for new student
- [x] NewStudent component will have a render function with div's and Material CSS library styling library applied

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [ ] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
